# Generated by Django 5.2.16 on 2026-09-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_assign_quotation_price_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-quotation_date', '-created_at'], 'permissions': [('import_quotation', 'Puede importar cotizaciones masivamente'), ('export_quotation', 'Puede exportar cotizaciones masivamente'), ('configure_quotation_document', 'Puede acceder a la configuración del documento de cotización'), ('manage_quotation_templates', 'Puede administrar las plantillas de cotización'), ('change_quotation_status', 'Puede cambiar el estado de una cotización'), ('change_quotation_item_price', 'Puede editar el precio unitario de los productos en una cotización'), ('view_dashboard', 'Puede ver el panel principal y sus reportes')]},
        ),
        migrations.AddField(
            model_name='quotation',
            name='import_reference',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
