# Generated by Django 5.2.16 on 2026-07-14 02:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import products.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('code', models.CharField(help_text='Ejemplo: CALEFONES, CALEFACTORES.', max_length=40, unique=True, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('code', models.CharField(help_text='Ejemplo: WHOLESALE, PREFERRED, REGULAR.', max_length=40, unique=True, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
            ],
            options={
                'verbose_name': 'nivel de precio',
                'verbose_name_plural': 'niveles de precio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('sku', models.CharField(help_text='Código interno único del producto.', max_length=80, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='código de barras')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=products.models.product_image_upload_path, verbose_name='imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='imagen principal')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posición')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagen del producto',
                'verbose_name_plural': 'imágenes de productos',
                'ordering': ['-is_primary', 'position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad mínima')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio unitario')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='válido desde')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='válido hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_prices_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='products.pricelevel', verbose_name='nivel de precio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'precio de producto',
                'verbose_name_plural': 'precios de productos',
                'ordering': ['product', 'price_level', 'minimum_quantity'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['deleted_at'], name='products_pr_deleted_efa2cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_product_name_per_category'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product', 'price_level', 'minimum_quantity'], name='products_pr_product_5887a9_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['is_active', 'valid_from'], name='products_pr_is_acti_461ae3_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'price_level', 'minimum_quantity'), name='unique_product_level_quantity_price'),
        ),
    ]
