# Generated by Django 5.2.16 on 2026-07-21 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_normal_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelevel',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='descuento automático (%)'),
        ),
    ]
