# Generated by Django 5.2.16 on 2026-07-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pricelevel_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelevel',
            name='discount_percent',
        ),
    ]
