# Generated by Django 5.2.16 on 2026-07-21 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_pricelevel_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelevel',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='descuento automático (%)'),
        ),
        migrations.AddField(
            model_name='pricelevel',
            name='minimum_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad mínima para aplicar la regla'),
        ),
    ]
