# Generated by Django 5.2.16 on 2026-07-25 13:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_initial_tiers_and_link_prices(apps, schema_editor):
    PriceLevel = apps.get_model('products', 'PriceLevel')
    PriceTier = apps.get_model('products', 'PriceTier')
    ProductPrice = apps.get_model('products', 'ProductPrice')
    for level in PriceLevel.objects.all():
        PriceTier.objects.get_or_create(price_level=level, minimum_quantity=1)
    for price in ProductPrice.objects.filter(price_tier__isnull=True):
        tier, _ = PriceTier.objects.get_or_create(
            price_level=price.price_level,
            minimum_quantity=price.minimum_quantity,
        )
        price.price_tier = tier
        price.save(update_fields=['price_tier'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_pricelevel_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelevel',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='pricelevel',
            name='minimum_quantity',
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='products.pricelevel')),
            ],
            options={
                'ordering': ['price_level__name', 'minimum_quantity'],
            },
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='products.pricetier', verbose_name='nivel por cantidad'),
        ),
        migrations.RunPython(create_initial_tiers_and_link_prices, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='pricetier',
            constraint=models.UniqueConstraint(fields=('price_level', 'minimum_quantity'), name='unique_price_tier_quantity'),
        ),
    ]
