"""Datos funcionales para probar los perfiles de acceso del CRM en desarrollo."""

ROLE_DEFINITIONS = (
    {
        "name": "Administrador",
        "code": "ADMIN",
        "description": "Acceso completo a la administración y operación del CRM.",
        "permissions": None,
    },
    {
        "name": "Comercial",
        "code": "SALES",
        "description": "Registra clientes y prepara cotizaciones usando el catálogo.",
        "permissions": (
            "clients.view_client",
            "clients.add_client",
            "clients.change_client",
            "clients.view_clienttype",
            "products.view_product",
            "products.view_pricelevel",
            "products.view_pricetier",
            "products.view_productprice",
            "quotations.view_quotation",
            "quotations.add_quotation",
            "quotations.change_quotation",
        ),
    },
    {
        "name": "Catálogo",
        "code": "CATALOG",
        "description": "Administra productos, categorías, precios e imágenes.",
        "permissions": (
            "products.view_product",
            "products.add_product",
            "products.change_product",
            "products.view_category",
            "products.add_category",
            "products.change_category",
            "products.view_pricelevel",
            "products.add_pricelevel",
            "products.change_pricelevel",
            "products.view_pricetier",
            "products.add_pricetier",
            "products.change_pricetier",
            "products.view_productprice",
            "products.add_productprice",
            "products.change_productprice",
            "products.view_productimage",
            "products.add_productimage",
            "products.change_productimage",
            "products.delete_productimage",
        ),
    },
    {
        "name": "Inventario",
        "code": "INVENTORY",
        "description": "Consulta existencias y registra movimientos de inventario.",
        "permissions": (
            "products.view_product",
            "inventory.view_warehouse",
            "inventory.add_warehouse",
            "inventory.change_warehouse",
            "inventory.view_stock",
            "inventory.add_stock",
            "inventory.change_stock",
            "inventory.view_stockmovement",
            "inventory.add_stockmovement",
        ),
    },
    {
        "name": "Consulta",
        "code": "VIEWER",
        "description": "Consulta información sin realizar cambios.",
        "permissions": (
            "clients.view_client",
            "clients.view_clienttype",
            "products.view_product",
            "products.view_category",
            "products.view_pricelevel",
            "products.view_pricetier",
            "products.view_productprice",
            "inventory.view_warehouse",
            "inventory.view_stock",
            "inventory.view_stockmovement",
            "quotations.view_quotation",
        ),
    },
)

DEMO_USERS = (
    {
        "username": "demo_admin",
        "email": "admin.demo@idesem.local",
        "first_name": "Andrea",
        "last_name": "Administración",
        "role_code": "ADMIN",
    },
    {
        "username": "demo_comercial",
        "email": "comercial.demo@idesem.local",
        "first_name": "Carla",
        "last_name": "Comercial",
        "role_code": "SALES",
    },
    {
        "username": "demo_catalogo",
        "email": "catalogo.demo@idesem.local",
        "first_name": "Pablo",
        "last_name": "Catálogo",
        "role_code": "CATALOG",
    },
    {
        "username": "demo_inventario",
        "email": "inventario.demo@idesem.local",
        "first_name": "Inés",
        "last_name": "Inventario",
        "role_code": "INVENTORY",
    },
    {
        "username": "demo_consulta",
        "email": "consulta.demo@idesem.local",
        "first_name": "Víctor",
        "last_name": "Consulta",
        "role_code": "VIEWER",
    },
)


SYSTEM_USERS = (
    {
        "username": "admin",
        "email": "admin@seed.idesem.local",
        "first_name": "Administrador",
        "last_name": "IDESEM",
        "role_code": "ADMIN",
    },
    {
        "username": "cajero",
        "email": "cajero@seed.idesem.local",
        "first_name": "Cajero",
        "last_name": "IDESEM",
        "role_code": "SALES",
    },
    {
        "username": "inventarios",
        "email": "inventarios@seed.idesem.local",
        "first_name": "Inventarios",
        "last_name": "IDESEM",
        "role_code": "INVENTORY",
    },
    {
        "username": "configuraciones",
        "email": "configuraciones@seed.idesem.local",
        "first_name": "Configuraciones",
        "last_name": "IDESEM",
        "role_code": "CATALOG",
    },
)
