"""Roles y usuarios iniciales del CRM IDESEM."""


ROLE_DEFINITIONS = (
    {
        "name": "Super Admin",
        "code": "ADMIN",
        "description": "Acceso completo a la administración y operación del CRM.",
        "permissions": None,
    },
    {
        "name": "Cajero",
        "code": "C001",
        "description": "Registra clientes, prepara cotizaciones y actualiza sus estados.",
        "permissions": (
            "clients.view_client",
            "clients.add_client",
            "clients.change_client",
            "clients.view_clienttype",
            "clients.add_clienttype",
            "products.view_product",
            "products.view_pricelevel",
            "products.view_pricetier",
            "products.view_productprice",
            "quotations.view_dashboard",
            "quotations.view_quotation",
            "quotations.add_quotation",
            "quotations.change_quotation",
            "quotations.change_quotation_status",
        ),
    },
    {
        "name": "Jefe",
        "code": "CJ001",
        "description": "Supervisa ventas, catálogo, inventario, almacenes y reportes.",
        "permissions": (
            "clients.view_client",
            "clients.add_client",
            "clients.change_client",
            "clients.delete_client",
            "clients.view_clienttype",
            "clients.add_clienttype",
            "clients.change_clienttype",
            "clients.delete_clienttype",
            "products.view_product",
            "products.add_product",
            "products.change_product",
            "products.delete_product",
            "products.view_category",
            "products.add_category",
            "products.change_category",
            "products.delete_category",
            "products.view_pricelevel",
            "products.add_pricelevel",
            "products.change_pricelevel",
            "products.delete_pricelevel",
            "products.view_pricetier",
            "products.add_pricetier",
            "products.change_pricetier",
            "products.delete_pricetier",
            "products.view_productprice",
            "products.add_productprice",
            "products.change_productprice",
            "products.delete_productprice",
            "products.view_productimage",
            "products.add_productimage",
            "products.change_productimage",
            "products.delete_productimage",
            "inventory.view_stock",
            "inventory.add_stock",
            "inventory.change_stock",
            "inventory.delete_stock",
            "inventory.view_stockmovement",
            "inventory.add_stockmovement",
            "inventory.change_stockmovement",
            "inventory.delete_stockmovement",
            "inventory.view_warehouse",
            "inventory.add_warehouse",
            "inventory.change_warehouse",
            "inventory.delete_warehouse",
            "quotations.view_dashboard",
            "quotations.view_quotation",
            "quotations.add_quotation",
            "quotations.change_quotation",
            "quotations.delete_quotation",
            "quotations.change_quotation_status",
            "quotations.configure_quotation_document",
            "quotations.manage_quotation_templates",
        ),
    },
    {
        "name": "Configuraciones",
        "code": "CONF001",
        "description": "Configura productos, categorías, precios y plantillas.",
        "permissions": (
            "products.view_product",
            "products.add_product",
            "products.change_product",
            "products.delete_product",
            "products.view_category",
            "products.add_category",
            "products.change_category",
            "products.delete_category",
            "products.view_pricelevel",
            "products.add_pricelevel",
            "products.change_pricelevel",
            "products.delete_pricelevel",
            "products.view_pricetier",
            "products.add_pricetier",
            "products.change_pricetier",
            "products.delete_pricetier",
            "products.view_productprice",
            "products.add_productprice",
            "products.change_productprice",
            "products.delete_productprice",
            "products.view_productimage",
            "products.add_productimage",
            "products.change_productimage",
            "products.delete_productimage",
            "quotations.configure_quotation_document",
            "quotations.manage_quotation_templates",
        ),
    },
)


SEED_USERS = (
    {
        "username": "cajero",
        "email": "cajero@seed.idesem.local",
        "first_name": "Cajero",
        "last_name": "IDESEM",
        "role_code": "C001",
    },
    {
        "username": "jefe",
        "email": "jefe@seed.idesem.local",
        "first_name": "Jefe",
        "last_name": "IDESEM",
        "role_code": "CJ001",
    },
    {
        "username": "configuraciones",
        "email": "configuraciones@seed.idesem.local",
        "first_name": "Configuraciones",
        "last_name": "IDESEM",
        "role_code": "CONF001",
    },
    {
        "username": "superadmin",
        "email": "superadmin@seed.idesem.local",
        "first_name": "Super",
        "last_name": "Admin",
        "role_code": "ADMIN",
        "is_staff": True,
        "is_superuser": True,
    },
)


LEGACY_SEED_USERNAMES = (
    "admin",
    "inventarios",
    "demo_admin",
    "demo_comercial",
    "demo_catalogo",
    "demo_inventario",
    "demo_consulta",
)
