# Generated by Django 5.2.16 on 2026-07-14 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
            ],
            options={
                'verbose_name': 'almacén',
                'verbose_name_plural': 'almacenes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='stock físico')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='stock reservado')),
                ('minimum_stock', models.PositiveIntegerField(default=0, verbose_name='stock mínimo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='products.product', verbose_name='producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouse', verbose_name='almacén')),
            ],
            options={
                'verbose_name': 'existencia',
                'verbose_name_plural': 'existencias',
                'ordering': ['warehouse', 'product'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='tipo de movimiento')),
                ('quantity_delta', models.IntegerField(help_text='Positivo para entradas y negativo para salidas.', verbose_name='variación de cantidad')),
                ('previous_quantity', models.PositiveIntegerField(verbose_name='cantidad anterior')),
                ('resulting_quantity', models.PositiveIntegerField(verbose_name='cantidad resultante')),
                ('reference', models.CharField(blank=True, help_text='Número de compra, venta, ajuste o documento relacionado.', max_length=120, verbose_name='referencia')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha del movimiento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stock', verbose_name='existencia')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', '-created_at'], name='inventory_s_stock_i_cee363_idx'), models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'), models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='stock_movement_delta_not_zero')],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_112b63_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity'], name='inventory_s_quantit_287c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['minimum_stock'], name='inventory_s_minimum_99227d_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_product_stock_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', models.F('reserved_quantity'))), name='reserved_stock_not_greater_than_quantity'),
        ),
    ]
