# Generated by Django 5.2.16 on 2026-07-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre o razón social')),
                ('tax_id', models.CharField(max_length=30, unique=True, verbose_name='NIT/CI')),
                ('department', models.CharField(max_length=80, verbose_name='departamento')),
                ('city_zone', models.CharField(max_length=120, verbose_name='ciudad/zona')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp')),
                ('client_type', models.CharField(choices=[('Distribuidor o mayorista', 'Distribuidor o mayorista'), ('Tienda o comercio', 'Tienda o comercio'), ('Técnico o instalador', 'Técnico o instalador'), ('Empresa o constructora', 'Empresa o constructora'), ('Institución o proyecto', 'Institución o proyecto')], max_length=80)),
                ('business_activity', models.CharField(max_length=200, verbose_name='rubro o actividad')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='products.pricelevel', verbose_name='nivel de precio')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['department'], name='clients_cli_departm_a9e753_idx'), models.Index(fields=['client_type'], name='clients_cli_client__1e0f73_idx'), models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx')],
            },
        ),
    ]
