# Generated by Django 5.2.16 on 2026-07-18 19:59

from django.db import migrations, models


DEFAULT_TYPES = [
    "Distribuidor o mayorista",
    "Tienda o comercio",
    "Técnico o instalador",
    "Empresa o constructora",
    "Institución o proyecto",
]


def seed_client_types(apps, schema_editor):
    ClientType = apps.get_model("clients", "ClientType")
    ClientType.objects.bulk_create([ClientType(name=name) for name in DEFAULT_TYPES])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tipo de cliente',
                'verbose_name_plural': 'tipos de cliente',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(max_length=80),
        ),
        migrations.RunPython(seed_client_types, migrations.RunPython.noop),
    ]
