# Generated by Django 5.2.16 on 2026-07-14 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
